---

services:
  state2slack:
    build: .
    image: state2slack
    container_name: state2slack
    restart: no
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./log:/app/log
